import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  FlatList,
  ActivityIndicator,
  Alert,
  Share,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons as Icon } from '@expo/vector-icons';
import * as FileSystem from 'expo-file-system/legacy';
import DataStore from '../utils/dataStore.js';

export default function ElectionResultScreen({ route, navigation }) {
  const { election: passedElection, electionId: passedId } = route.params;
  const [election, setElection] = useState(passedElection || null);
  const [loading, setLoading] = useState(!passedElection);
  const [downloading, setDownloading] = useState(false);
  const [sharing, setSharing] = useState(false);

  useEffect(() => {
    if (!passedElection && passedId) {
      loadElection(passedId);
    } else if (passedElection) {
      setElection(passedElection);
      setLoading(false);
    }
  }, []);

  const loadElection = async (id) => {
    setLoading(true);
    const fetched = await DataStore.getElectionById(id);
    if (fetched) {
      setElection(fetched);
    }
    setLoading(false);
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#6A1B9A" />
        <Text style={styles.loadingText}>Loading results...</Text>
      </View>
    );
  }

  if (!election) {
    return (
      <View style={styles.loadingContainer}>
        <Icon name="alert-circle" size={60} color="#FF6F00" />
        <Text style={styles.loadingText}>Election not found</Text>
        <TouchableOpacity
          style={styles.backBtn}
          onPress={() => navigation.goBack()}
        >
          <Text style={styles.backBtnText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const winners = election.getWinners();
  const sortedCandidates = [...election.candidates].sort(
    (a, b) => (b.vote_count || 0) - (a.vote_count || 0)
  );
  const isFaculty = DataStore.currentUserRole === 'faculty';

  const totalVotes = election.currentVoteCount || 0;
  const isTie = winners.length > 1;
  const maxVoteCount = winners.length > 0 ? (winners[0].vote_count || 0) : 0;

  const sanitizeForFileName = (value) =>
    String(value || 'election')
      .trim()
      .replace(/[<>:"/\\|?*\x00-\x1F]/g, '')
      .replace(/\s+/g, '_')
      .slice(0, 40);

  const escapeCsvValue = (value) => {
    if (value === null || value === undefined) return '';
    const stringValue = String(value);
    if (/[",\n]/.test(stringValue)) {
      return `"${stringValue.replace(/"/g, '""')}"`;
    }
    return stringValue;
  };

  const buildCsvReport = () => {
    const now = new Date();
    const winnerNames = winners.map((winner) => winner.name).join(', ');
    const turnoutPercent = election.maxVotes > 0
      ? ((election.currentVoteCount / election.maxVotes) * 100).toFixed(2)
      : '0.00';

    const rows = [
      ['Election Title', election.title],
      ['Election ID', election.id],
      ['Status', election.isClosed ? 'Closed' : 'Active'],
      ['Created At', new Date(election.createdAt).toLocaleString()],
      ['Report Generated At', now.toLocaleString()],
      ['Generated By (Reg No)', DataStore.currentUser?.regNo || 'Unknown'],
      ['Generated By (Name)', DataStore.currentUser?.fullName || 'Unknown'],
      ['Total Votes', election.currentVoteCount],
      ['Maximum Votes', election.maxVotes],
      ['Turnout %', turnoutPercent],
      ['Winner(s)', winnerNames || 'No winner'],
      [],
      ['Rank', 'Candidate ID', 'Candidate Name', 'Qualification', 'Votes', 'Vote %'],
      ...sortedCandidates.map((candidate, index) => {
        const voteCount = candidate.vote_count || 0;
        const votePercentage = totalVotes > 0
          ? ((voteCount / totalVotes) * 100).toFixed(2)
          : '0.00';
        return [
          index + 1,
          candidate.id,
          candidate.name,
          candidate.qualification || '',
          voteCount,
          votePercentage,
        ];
      }),
    ];

    return rows
      .map((row) => row.map(escapeCsvValue).join(','))
      .join('\n');
  };

  const generateReportFile = async () => {
    if (!FileSystem.documentDirectory) {
      throw new Error('File system is unavailable on this device');
    }

    const csvContent = buildCsvReport();
    const fileName = `${sanitizeForFileName(election.title)}_${election.id}_results.csv`;
    const directoryUri = `${FileSystem.documentDirectory}reports/`;

    const dirInfo = await FileSystem.getInfoAsync(directoryUri);
    if (!dirInfo.exists) {
      await FileSystem.makeDirectoryAsync(directoryUri, { intermediates: true });
    }

    const fileUri = `${directoryUri}${fileName}`;
    await FileSystem.writeAsStringAsync(fileUri, csvContent, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    return { fileName, fileUri };
  };

  const handleDownloadReport = async () => {
    if (!isFaculty || !election.isClosed) {
      return;
    }

    setDownloading(true);
    try {
      const { fileName } = await generateReportFile();

      Alert.alert(
        'Report Downloaded',
        `Election report saved successfully.\n\nFile: ${fileName}\nLocation: App documents/reports`
      );
    } catch (error) {
      console.error('Download report error:', error);
      Alert.alert('Download Failed', 'Could not download election report. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  const handleShareReport = async () => {
    if (!isFaculty || !election.isClosed) {
      return;
    }

    setSharing(true);
    try {
      const { fileName, fileUri } = await generateReportFile();
      await Share.share({
        title: 'Election Results Report',
        message: `Election report: ${fileName}\n${fileUri}`,
        url: fileUri,
      });
    } catch (error) {
      console.error('Share report error:', error);
      Alert.alert('Share Failed', 'Could not share election report. Please try again.');
    } finally {
      setSharing(false);
    }
  };

  const renderCandidate = ({ item, index }) => {
    const isWinner = winners.some((w) => w.id === item.id);
    const voteCount = item.vote_count || 0;
    const percentage = totalVotes > 0
      ? ((voteCount / totalVotes) * 100).toFixed(1)
      : '0.0';

    return (
      <View style={[styles.candidateCard, isWinner && styles.winnerCandidateCard]}>
        <View style={styles.candidateHeader}>
          <View style={styles.positionBadge}>
            <Text style={[styles.positionText, isWinner && styles.winnerPositionText]}>
              #{index + 1}
            </Text>
          </View>

          <LinearGradient
            colors={isWinner ? ['#FFD700', '#FFA000'] : ['#E0E0E0', '#BDBDBD']}
            style={styles.candidateAvatar}
          >
            <Text style={styles.candidateInitial}>
              {item.name[0].toUpperCase()}
            </Text>
          </LinearGradient>

          <View style={styles.candidateInfo}>
            <Text style={[styles.candidateName, isWinner && styles.winnerName]}>
              {item.name}
            </Text>
            {item.qualification && (
              <View style={styles.qualificationRow}>
                <Icon name="school" size={12} color="#666666" />
                <Text style={styles.qualification}>{item.qualification}</Text>
              </View>
            )}
            <View style={styles.voteRow}>
              <Icon name="chart-bar" size={14} color={isWinner ? '#FFD700' : '#666666'} />
              <Text style={[styles.voteText, isWinner && styles.winnerVoteText]}>
                {voteCount} {voteCount === 1 ? 'vote' : 'votes'} ({percentage}%)
              </Text>
            </View>
          </View>

          {isWinner && (
            <View style={styles.trophyContainer}>
              <Icon name="trophy" size={32} color="#FFD700" />
            </View>
          )}
        </View>

        <View style={styles.progressBarContainer}>
          <LinearGradient
            colors={isWinner ? ['#FFD700', '#FFA000'] : ['#6A1B9A', '#9C27B0']}
            style={[styles.progressBar, { width: `${Math.max(percentage, 2)}%` }]}
          />
        </View>
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <LinearGradient colors={['#6A1B9A', '#9C27B0']} style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Icon name="arrow-left" size={24} color="#FFFFFF" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Election Results</Text>
        <View style={{ width: 24 }} />
      </LinearGradient>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        <LinearGradient colors={['#6A1B9A', '#9C27B0']} style={styles.electionInfoCard}>
          <View style={styles.electionIconRow}>
            <View style={styles.electionIconContainer}>
              <Icon name="vote" size={28} color="#FFFFFF" />
            </View>
            <View style={styles.electionTitleContainer}>
              <Text style={styles.electionTitle}>{election.title}</Text>
              <Text style={styles.electionSubtitle}>Election ID: {election.id}</Text>
            </View>
          </View>

          <View style={styles.infoBadgesRow}>
            <View style={styles.infoBadge}>
              <Icon name="account-group" size={14} color="#FFFFFF" />
              <Text style={styles.badgeText}>{election.currentVoteCount}/{election.maxVotes}</Text>
            </View>
            <View style={styles.infoBadge}>
              <Icon
                name={election.isClosed ? 'lock' : 'check-circle'}
                size={14}
                color="#FFFFFF"
              />
              <Text style={styles.badgeText}>
                {election.isClosed ? 'Closed' : 'Active'}
              </Text>
            </View>
            <View style={styles.infoBadge}>
              <Icon name="calendar" size={14} color="#FFFFFF" />
              <Text style={styles.badgeText}>
                {new Date(election.createdAt).toLocaleDateString()}
              </Text>
            </View>
          </View>
        </LinearGradient>

        {election.candidates.length > 0 && totalVotes > 0 ? (
          <LinearGradient
            colors={isTie ? ['#FF9800', '#FB8C00'] : ['#FFD700', '#FFA000']}
            style={styles.winnerCard}
          >
            <View style={styles.winnerIconContainer}>
              <Icon name={isTie ? 'equal' : 'trophy'} size={48} color="#FFFFFF" />
            </View>
            <Text style={styles.winnerTitle}>
              {isTie ? 'It\'s a Tie' : 'Winner'}
            </Text>
            <View style={styles.winnerNamesContainer}>
              {isTie ? (
                winners.map((winner, index) => (
                  <View key={index} style={styles.winnerNameRow}>
                    <View style={styles.winnerDot} />
                    <Text style={styles.winnerNameText}>{winner.name}</Text>
                  </View>
                ))
              ) : (
                <Text style={styles.winnerNameText}>{winners[0]?.name}</Text>
              )}
            </View>
            <View style={styles.winnerVotesBadge}>
              <Icon name="heart" size={16} color="#FFFFFF" />
              <Text style={styles.winnerVotesText}>
                {maxVoteCount} {maxVoteCount === 1 ? 'Vote' : 'Votes'}
              </Text>
            </View>
          </LinearGradient>
        ) : election.candidates.length > 0 && totalVotes === 0 ? (
          <View style={styles.noVotesCard}>
            <View style={styles.noVotesIconContainer}>
              <Icon name="clock-outline" size={40} color="#FF9800" />
            </View>
            <Text style={styles.noVotesTitle}>No Votes Cast Yet</Text>
            <Text style={styles.noVotesSubtitle}>Results will appear once voting begins</Text>
          </View>
        ) : null}

        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Candidate Rankings</Text>
          <View style={styles.sectionBadge}>
            <Text style={styles.sectionBadgeText}>{election.candidates.length}</Text>
          </View>
        </View>

        {election.candidates.length === 0 ? (
          <View style={styles.emptyState}>
            <Icon name="account-off" size={80} color="#CCCCCC" />
            <Text style={styles.emptyTitle}>No Candidates</Text>
            <Text style={styles.emptySubtitle}>No candidates have been added to this election yet</Text>
          </View>
        ) : (
          <FlatList
            data={sortedCandidates}
            renderItem={renderCandidate}
            keyExtractor={(item) => item.id}
            scrollEnabled={false}
          />
        )}

        {election.candidates.length > 0 && (
          <View style={styles.statsCard}>
            <View style={styles.statsHeaderRow}>
              <View style={styles.statsIconContainer}>
                <Icon name="chart-line" size={22} color="#6A1B9A" />
              </View>
              <Text style={styles.statsTitle}>Election Statistics</Text>
            </View>

            <View style={styles.statsGrid}>
              <View style={styles.statItem}>
                <View style={[styles.statIconCircle, { backgroundColor: '#6A1B9A15' }]}>
                  <Icon name="vote" size={20} color="#6A1B9A" />
                </View>
                <Text style={styles.statValue}>{election.currentVoteCount}</Text>
                <Text style={styles.statLabel}>Total Votes</Text>
              </View>

              <View style={styles.statItem}>
                <View style={[styles.statIconCircle, { backgroundColor: '#FF6F0015' }]}>
                  <Icon name="account-multiple" size={20} color="#FF6F00" />
                </View>
                <Text style={styles.statValue}>{election.candidates.length}</Text>
                <Text style={styles.statLabel}>Candidates</Text>
              </View>

              <View style={styles.statItem}>
                <View style={[styles.statIconCircle, { backgroundColor: '#4CAF5015' }]}>
                  <Icon name="poll" size={20} color="#4CAF50" />
                </View>
                <Text style={styles.statValue}>
                  {election.maxVotes > 0
                    ? ((election.currentVoteCount / election.maxVotes) * 100).toFixed(0)
                    : 0}%
                </Text>
                <Text style={styles.statLabel}>Turnout</Text>
              </View>

              <View style={styles.statItem}>
                <View style={[styles.statIconCircle, { backgroundColor: '#2196F315' }]}>
                  <Icon name="chart-bar" size={20} color="#2196F3" />
                </View>
                <Text style={styles.statValue}>
                  {election.candidates.length > 0
                    ? (election.currentVoteCount / election.candidates.length).toFixed(1)
                    : 0}
                </Text>
                <Text style={styles.statLabel}>Avg/Candidate</Text>
              </View>
            </View>
          </View>
        )}

        {isFaculty && election.isClosed && (
          <View style={styles.reportActionsRow}>
            <TouchableOpacity
              style={[
                styles.downloadButton,
                styles.reportActionButton,
                downloading && styles.downloadButtonDisabled,
              ]}
              onPress={handleDownloadReport}
              disabled={downloading || sharing}
            >
              {downloading ? (
                <ActivityIndicator size="small" color="#FFFFFF" />
              ) : (
                <Icon name="download" size={18} color="#FFFFFF" />
              )}
              <Text style={styles.downloadButtonText}>
                {downloading ? 'Downloading...' : 'Download'}
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[
                styles.shareButton,
                styles.reportActionButton,
                sharing && styles.downloadButtonDisabled,
              ]}
              onPress={handleShareReport}
              disabled={sharing || downloading}
            >
              {sharing ? (
                <ActivityIndicator size="small" color="#FFFFFF" />
              ) : (
                <Icon name="share-variant" size={18} color="#FFFFFF" />
              )}
              <Text style={styles.downloadButtonText}>
                {sharing ? 'Sharing...' : 'Share Report'}
              </Text>
            </TouchableOpacity>
          </View>
        )}

        <View style={{ height: 20 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  loadingText: { marginTop: 16, fontSize: 16, color: '#666666' },
  backBtn: {
    marginTop: 20,
    backgroundColor: '#6A1B9A',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
  },
  backBtnText: { color: '#FFFFFF', fontWeight: 'bold' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  backButton: { padding: 4 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#FFFFFF' },
  content: { flex: 1, padding: 16 },
  electionInfoCard: {
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    elevation: 4,
  },
  electionIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  electionIconContainer: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    padding: 10,
    marginRight: 12,
  },
  electionTitleContainer: { flex: 1 },
  electionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  electionSubtitle: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
  },
  infoBadgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  badgeText: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 12 },
  winnerCard: {
    padding: 24,
    borderRadius: 20,
    alignItems: 'center',
    marginBottom: 16,
    elevation: 6,
  },
  winnerIconContainer: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 50,
    padding: 16,
    marginBottom: 12,
  },
  winnerTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  winnerNamesContainer: {
    alignItems: 'center',
    marginBottom: 12,
  },
  winnerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 4,
  },
  winnerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
    marginRight: 8,
  },
  winnerNameText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  winnerVotesBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  winnerVotesText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  noVotesCard: {
    backgroundColor: '#FFF8E1',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#FFE082',
  },
  noVotesIconContainer: {
    backgroundColor: '#FFE082',
    borderRadius: 50,
    padding: 12,
    marginBottom: 12,
  },
  noVotesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F57C00',
    marginBottom: 4,
  },
  noVotesSubtitle: {
    fontSize: 13,
    color: '#FB8C00',
    textAlign: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#424242',
  },
  sectionBadge: {
    backgroundColor: '#6A1B9A',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  sectionBadgeText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  candidateCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'transparent',
    elevation: 2,
  },
  winnerCandidateCard: {
    borderColor: '#FFD700',
    backgroundColor: '#FFFBF0',
    elevation: 4,
  },
  candidateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  positionBadge: {
    backgroundColor: '#6A1B9A',
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  positionText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  winnerPositionText: {
    color: '#FFFFFF',
  },
  candidateAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  candidateInitial: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  candidateInfo: { flex: 1 },
  candidateName: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 4,
  },
  winnerName: {
    color: '#F57C00',
  },
  qualificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  qualification: {
    fontSize: 11,
    color: '#666666',
    fontStyle: 'italic',
  },
  voteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  voteText: {
    fontSize: 13,
    color: '#666666',
    fontWeight: '500',
  },
  winnerVoteText: {
    color: '#F57C00',
    fontWeight: 'bold',
  },
  trophyContainer: {
    marginLeft: 8,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 4,
  },
  statsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginTop: 4,
    elevation: 2,
  },
  statsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  statsIconContainer: {
    backgroundColor: '#6A1B9A10',
    borderRadius: 10,
    padding: 8,
    marginRight: 12,
  },
  statsTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#333333',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  statItem: {
    width: '48%',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  statIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
  emptyState: {
    backgroundColor: '#FAFAFA',
    borderRadius: 16,
    padding: 40,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#666666',
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: '#999999',
    textAlign: 'center',
    marginTop: 8,
  },
  downloadButton: {
    marginTop: 16,
    backgroundColor: '#6A1B9A',
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    elevation: 3,
  },
  shareButton: {
    marginTop: 16,
    backgroundColor: '#8E24AA',
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    elevation: 3,
  },
  reportActionsRow: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 10,
  },
  reportActionButton: {
    marginTop: 0,
    flex: 1,
  },
  downloadButtonDisabled: {
    opacity: 0.7,
  },
  downloadButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
});
